### ISSUE TITLE
Error when create android project

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/khamake#1]
I cloned the Empty repo, when I try to create a android project, I'm getting this error (complete log):

C:\Dev\Projetos\Kha\Empty>node Kha/make android
Graphics: direct3d9
Vr API is: none
Generating Kha project.
Assets done.
Haxe stderr: ..\Kha\Backends\Kore/kha/Starter.hx:76: characters 34-60 : Type not found : CardboardVrInterface

Haxe process exited with code 1
VrApi (main.js): undefined
korefile found, generating build files.
Generating Android solution
.
.
.
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\Data\android\.clas
spath'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.exports.copyIfDifferent (C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\Files.js:60:38)
    at ExporterAndroid.exportSolution (C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\ExporterAndroid.js:25
:11)
    at exportKakeProject (C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\main.js:178:11)
    at exportProject (C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\main.js:190:10)
    at Object.exports.run (C:\Dev\Projetos\Kha\Empty\Kha\Kore\Tools\koremake\main.js:215:2)
    at C:\Dev\Projetos\Kha\Empty\Kha\Tools\khamake\main.js:412:35
    at ChildProcess.<anonymous> (C:\Dev\Projetos\Kha\Empty\Kha\Tools\khamake\Haxe.js:27:3)

**Comment by RobDangerous** [comment]
Thanks, fixed.
