### ISSUE TITLE
error when there is no assets field in project.kha

### ISSUE THREAD

**Issue by JeriXNet** [KTXSoftware/khamake#15]
```
c:\path\to\prj\Kha\Tools\khamake\main.js:212
        if (index >= assets.length) {
                           ^
TypeError: Cannot read property 'length' of undefined
    at exportAssets (c:\path\to\prj\Kha\Tools\khamake\main.js:212:21)
    at exportKhaProject (c:\path\to\prj\Kha\Tools\khamake\main.js:595:2)
    at exportProject (c:\path\to\prj\Kha\Tools\khamake\main.js:664:3)
    at Object.exports.run (c:\path\to\prj\Kha\Tools\khamake\main.js:752:2)
    at Object.<anonymous> (c:\path\to\prj\Kha\Tools\khamake\khamake.js:498:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by JeriXNet** [comment]
And there is crash in kore Loader when there is no `rooms` field in `project.kha`

**Comment by RobDangerous** [comment]
I'll add error messages for that but please stop destroying innocent project.kha files, what did they ever do to you?

**Comment by JeriXNet** [comment]
sorry if I'm being pedantic :)

**Comment by RobDangerous** [comment]
Oh that's ok :) Catching things like that will make Kha look more robust and mature (looking at you, XCode, with your silly error messages when your project files are broken).
