### ISSUE TITLE
Cannot use haxelib installed as dev (for example from github)

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/khamake#6]
The error is :
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\HaxeToolkit\haxe\lib\khage\.current'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at exportKhaProject (C:\Development\haxe\kha_test\Kha\Tools\khamake\main.js:502:24)
    at exportProject (C:\Development\haxe\kha_test\Kha\Tools\khamake\main.js:638:3)
    at Object.exports.run (C:\Development\haxe\kha_test\Kha\Tools\khamake\main.js:723:2)
    at Object.<anonymous> (C:\Development\haxe\kha_test\Kha\Tools\khamake\khamake.js:498:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by RobDangerous** [comment]
What exactly are you doing there, are you pointing it to the git version? Because that is not supported.

**Comment by wighawag** [comment]
yes I installed my lib via 
```
haxelib git khage https://github.com/wighawag/khage
```

but since git use the dev feature of haxelib, this should also be a problem for
```
haxelib dev ...
```

Do you plan to support it ?

**Comment by RobDangerous** [comment]
Ah, thought you wanted to use Kha itself this way (which does not work because the haxelib version includes a local copy of node and the git version doesn't). Haxelib dev/git for other libs, that I can do.

**Comment by wighawag** [comment]
Cool, thanks
