### ISSUE TITLE
Can't build for Windows

### ISSUE THREAD

**Issue by hammeron-art** [KTXSoftware/khamake#83]
Can't build for Windows.
More accurately, it don't create the project solution.

Node v6.9.1
```node
Compiling code.
korefile found.
Creating Windows project files.
ReferenceError: __dirname is not defined
    at eval (eval at createProject (Kha\Kore\Tools\koremake\out\Solution.js:85:23), <anonymous>:3:34)
    at Function.createProject (Kha\Kore\Tools\koremake\out\Solution.js:85:103)
    at eval (eval at createSolution (Kha\Kore\Tools\koremake\out\Solution.js:93:24), <anonymous>:8:32)
    at Function.createSolution (Kha\Kore\Tools\koremake\out\Solution.js:93:130)
    at Function.create (Kha\Kore\Tools\koremake\out\Solution.js:117:33)
    at exportKoremakeProject (Kha\Kore\Tools\koremake\out\main.js:149:40)
    at exportProject (Kha\Kore\Tools\koremake\out\main.js:216:16)
    at Object.<anonymous> (Kha\Kore\Tools\koremake\out\main.js:271:24)
    at next (native)
    at Kha\Kore\Tools\koremake\out\main.js:7:65
```

**Comment by RobDangerous** [comment]
Tell me more about it. What version of Kha do you use? What project do you try to compile?

**Comment by hammeron-art** [comment]
Last commits
Kha c7c95f4a75413bbd5e858cb5809f9b880a83dd89
khamake bc7a9a134f413aa36f67d0321ce50b251e12df98

I can reproduce it with the Empty project in Kha/Tests

**Comment by RobDangerous** [comment]
I think your Kore submodule is not up to date. The mentioned Solution.js doesn't exist anymore. Have a look at the "Updating Kha" section at https://github.com/KTXSoftware/Kha/wiki/Getting-Started

**Comment by hammeron-art** [comment]
I'm getting really stream behavior with koremake.
It's updated and git tells me that everything is fine but the koremake directory don't change.
I can delete all files and git still tell me that there's no changes...

**Comment by hammeron-art** [comment]
I tested with a fresh clone from the original repository of Kha and it works.
Because the submodule structure is set up with relative paths I'm with some difficult because the origin points to a fork.
